---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
      
subject:
  words: I,You,He,She,It

verb:  
  words: ran,knew,had,saw,bought

article:
  words: a,the

adjective:
  words: reasonable,leaky,suspicious,ordinary,unlikely

noun:
  words: boat,book,vote,seat,backpack,partition,groundhog  
